--
-- Created by IntelliJ IDEA.
-- User: moyong
-- Date: 2019/9/17
-- Time: 13:14
-- To change this template use File | Settings | File Templates.
-- redis-lua 不支持 require dofile
-- 数组值转化为字典
-- 数组值转化为字典
